# Generated by Django 3.2.12 on 2022-05-12 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 17, 22, 35, 914450, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
